

[storage]
enabled = true
# The maximum file size allowed (e.g. "5MB", "500KB").
file_size_limit = "100MiB"
[storage.buckets.images]
public = false



# Staging-specific configuration
[remotes.staging]
project_id = "hzhylvgckmypslbzkhsq"

[remotes.staging.storage]
enabled = true
file_size_limit = "100MiB"
[remotes.staging.storage.buckets.images]
public = false
file_size_limit = "70MiB"
[remotes.staging.storage.buckets.subcriptions]
public = false
file_size_limit = "40MiB"
[remotes.staging.storage.buckets.krishna]
public = false
file_size_limit = "30MiB"
[remotes.staging.storage.buckets.subscriptions]
public = false
file_size_limit = "7MiB"
