



# Staging-specific configuration
[remotes.staging]
project_id = "wpcklsnbhsgliuecmyql"

[remotes.staging.storage]
enabled = true
file_size_limit = "100MiB"
[remotes.staging.storage.buckets.images]
public = false

