

[storage]
enabled = true
# The maximum file size allowed (e.g. "5MB", "500KB").
file_size_limit = "100MiB"
[storage.buckets.images]
public = false
[storage.buckets.subscriptions]
public = false



# Staging-specific configuration
[remotes.staging]
project_id = "wpcklsnbhsgliuecmyql"

[remotes.staging.storage]
enabled = true
file_size_limit = "100MiB"
[remotes.staging.storage.buckets.images]
public = false

