
# Staging-specific configuration
[remotes.staging]
project_id = "hzhylvgckmypslbzkhsq"

[remotes.staging.storage]
enabled = true
file_size_limit = "100MiB"
[remotes.staging.storage.buckets.images]
public = false
file_size_limit = "70MiB"
[remotes.staging.storage.buckets.subcriptions]
public = false
file_size_limit = "40MiB"
[remotes.staging.storage.buckets.krishna]
public = false
file_size_limit = "30MiB"
[remotes.staging.storage.buckets.subscriptions]
public = false
file_size_limit = "7MiB"

# Production-specific configuration
[remotes.production]
project_id = "wpcklsnbhsgliuecmyql"

[remotes.production.storage]
enabled = true
file_size_limit = "240MiB"
[remotes.production.storage.buckets.images]
public = false
file_size_limit = "171MiB"
[remotes.production.storage.buckets.subcriptions]
public = false
file_size_limit = "101MiB"
[remotes.production.storage.buckets.krishna]
public = false
file_size_limit = "110MiB"
[remotes.production.storage.buckets.subscriptions]
public = false
file_size_limit = "13MiB"
